name: Node.js CI

on:
  push:
    branches:
      - master  # Run CI only when code is pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Check for the frontend package.json
      - name: Check frontend package.json existence
        run: ls -la client/ped_app

      # Frontend steps
      - name: Install frontend dependencies
        working-directory: client/ped_app
        run: npm install

      - name: Run frontend tests
        working-directory: client/ped_app
        run: npm test

      - name: Build frontend project
        working-directory: client/ped_app
        run: npm run build

      # Check for the backend package.json
      - name: Check backend package.json existence
        run: ls -la server

      # Backend steps (if applicable)
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Run backend tests
        working-directory: server
        run: npm test

      - name: Build backend project
        working-directory: server
        run: npm run build
