name: Node.js CI

on:
  push:
    branches:
      - master  # Run CI only when code is pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache frontend dependencies
      - name: Cache frontend dependencies
        uses: actions/cache@v2
        with:
          path: client/ped_app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/ped_app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Check frontend package.json existence
      - name: Check frontend package.json existence
        run: |
          if [ ! -f client/ped_app/package.json ]; then
            echo "package.json not found in client/ped_app!"
            exit 1
          fi

      # Frontend steps
      - name: Install frontend dependencies
        working-directory: client/ped_app
        run: npm install

      - name: Run frontend tests
        working-directory: client/ped_app
        run: npm test

      - name: Build frontend project
        working-directory: client/ped_app
        run: npm run build

      # Cache backend dependencies
      - name: Cache backend dependencies
        uses: actions/cache@v2
        with:
          path: server/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Check backend package.json existence
      - name: Check backend package.json existence
        run: |
          if [ ! -f server/package.json ]; then
            echo "package.json not found in server!"
            exit 1
          fi

      # Backend steps
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Run backend tests
        working-directory: server
        run: npm test
